### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by savy-91** [Mindinventory/image_cropping#1]
Hi! First of all, thanks for this package!

I am experiencing an issue when using it in an application that must support also landscape mode, when the image_cropping  screen pops up it will move to portrait mode and once it's done it will not go back to landscape.

Would it be possible for you to also support landscape mode?

**Comment by mi-ghanshyam** [comment]
@savy-91  added support for landscape mode in `image_cropping: 0.0.8` please have a look.
I am happy to help you if required.
Thanks!
