### ISSUE TITLE
it reduces the size of the image 

### ISSUE THREAD

**Issue by HKTareen** [Mindinventory/image_cropping#10]
I uploaded a 7MB size of image and it just reduced the size to 1.8 mb even i selected the full area

**Comment by abrarmalekji345** [comment]
Hi,
it is because of jpg compression at the end, we will add more compression options to choose from.
Thank you

**Comment by abrarmalekji345** [comment]
@HKTareen you can now do png compression.
please update the package, if the platform is web, don't forget to update worker.js.
Thank you
