### ISSUE TITLE
[Web] how to add worker.js, worker.js.deps, worker.js.map in your project's root ?

### ISSUE THREAD

**Issue by Joseph-Nathan** [Mindinventory/image_cropping#11]
how to add worker.js, worker.js.deps, worker.js.map in your project's root ?

**Comment by abrarmalekji345** [comment]
Hello
you only have to add the worker.js file into the root directory, it is in the root of the package.
hope this helps

**Comment by Joseph-Nathan** [comment]
thanks ,
