### ISSUE TITLE
Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by EBBozkurt** [Mindinventory/image_cropping#13]
https://github.com/Mindinventory/image_cropping/blob/master/lib/image_cropping.dart 

remove old one :
      WidgetsBinding.instance?.addPostFrameCallback((timeStamp) async {
        topViewHeight = stackGlobalKey.globalPaintBounds?.top ?? 0;
      });

replace with:
      WidgetsBinding.instance.addPostFrameCallback((timeStamp) async {
        topViewHeight = stackGlobalKey.globalPaintBounds?.top ?? 0;
      });

Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.

![image](https://user-images.githubusercontent.com/50709618/170691903-59a1b92f-2b30-46fb-9c09-332cc8f9f1b2.png)

**Comment by abrarmalekji345** [comment]
@EBBozkurt done 👍
