### ISSUE TITLE
want to cropper set on whole image instead of center

### ISSUE THREAD

**Issue by YogitaPat** [Mindinventory/image_cropping#15]
Hello Team,

I need some help. I want cropper set on whole image base on image height and width how to achieve it using current code and which file /function need to changes also i need x & y starting position 0,0 .please team help me out.

Thanks ,
![Screenshot_1](https://user-images.githubusercontent.com/92594886/179169618-a484ae62-a3b1-4825-bca3-a89a11823a40.png)
![Screenshot_2](https://user-images.githubusercontent.com/92594886/179169627-b7882518-4b44-4cb4-842d-c51d719b4512.png)

Yogita

**Comment by AnujMI297** [comment]
@YogitaPat we haven't yet given the provision of knowing the position. But still, if you require it you can have a look inside the file `lib/widgets/crop_image_view.dart` where we are handling the whole logic behind the positions and dragging.

**Comment by deep-mindinventory** [comment]
We hope provided information to @YogitaPat is fine. Close issue due to no response. Kindly reopen if needed.
