### ISSUE TITLE
It doesn't support web on flutter sdk 3.0.0

### ISSUE THREAD

**Issue by scrtkr** [Mindinventory/image_cropping#16]
It doesn't support web on flutter sdk 3.0.0

**Comment by abrarmalekji345** [comment]
hi @alexlozdev, I just checked with flutter - 3.3.0, and it is working.
please verify if you have added worker.js in the root directory. 
for more info go through readme.

**Comment by abrarmalekji345** [comment]
@alexlozdev  for now, I am closing this issue.
