### ISSUE TITLE
Works on Android but on web just getting circular progress indicator

### ISSUE THREAD

**Issue by jimmyff** [Mindinventory/image_cropping#17]
Hi, thank you for sharing this package.

It is working for me on android but when I deploy to web, when I initiate the plugin I just get a new screen with a circular progress indicator. There are no errors showing in the console, the console message says: `blob:https://foobar.web.app/69a6817b-a37b-478a-8b04-976d41796cf5`. I have tried various images at different sizes and always get the same result.

Also on android I've found large images (multiple mb) cause the plugin to hang, sometimes crash. Is this something you can optimise?

Thanks

**Comment by tanergun** [comment]
same issue

**Comment by AnujMI297** [comment]
@jimmyff @tanergun We are unable to reproduce this same problem for the web, can you please share the steps to reproduce this issue or can you provide us with more detail about this?

**Comment by deep-mindinventory** [comment]
Close issue due to no response. Kindly reopen if needed.
