### ISSUE TITLE
Increasing the "initial" size of the crop area, Rotation issues On mac and windows, Embedding the widget

### ISSUE THREAD

**Issue by PavieOlivier** [Mindinventory/image_cropping#18]
- I**nitial size is too small:** As you can see from the image below, the crop area is too small, is there a way to provide a bigger size?

![Screenshot 2023-03-08 at 11 02 39 AM](https://user-images.githubusercontent.com/53576266/223627747-1c95a9a4-ee76-4c16-9dd4-79a42391b70c.png)

- **rotation issue:** When the crop area is big and the image is rotated, the crop area does not adjust until you try to resize it yourself, and when you try it flickers 

![Screenshot 2023-03-08 at 11 04 55 AM](https://user-images.githubusercontent.com/53576266/223628062-0e46bdfc-9c41-497d-b676-e3bad6e00d3a.png)

Is there a way to fix it??

- **embedding the widge**t: I tried having a look at your code base, and I saw that there is a view that I can call directly, But when I do that, the image has an offset towards the left and the crop area seems blocked ( since I cannot size on the left), I think this might be due to the SafeArea... I am not sure....

**Comment by AnujMI297** [comment]
@PavieOlivier By default we are giving the size of 1:1 which has the crop area as shown in the attachment below, and the size shown in your attached picture does seem like it is 16:9 or free ratio. Now with that much ratio (that is 16:9), the crop area is proper so the thing you can do is manually drag to alter the size.

![Screenshot 2023-05-25 at 3 05 09 PM](https://github.com/Mindinventory/image_cropping/assets/97672970/a500623b-7ba6-47dc-a3f1-ca020696c9ba)

**Comment by AnujMI297** [comment]
@PavieOlivier and for the second issue we haven't yet given the functionality for resizing automatically on the basis of orientation change, but as of now, you can change the size manually.

**Comment by deep-mindinventory** [comment]
Close issue due to no response. Kindly reopen if needed.
