### ISSUE TITLE
Choosing image from gallery using file picker package to image_cropping package

### ISSUE THREAD

**Issue by AccruonSahin** [Mindinventory/image_cropping#19]
Choosing image from gallery using file picker package to image_cropping package 

E/flutter (11146): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (11146): #0      ImageProcess.getCompressedImage (package:image_cropping/common/compress_process.dart:65:58)
E/flutter (11146): #1      ImageProcess.compress (package:image_cropping/common/compress_process.dart:28:26)
E/flutter (11146): #2      _ImageCroppingScreenState._generateLibraryImage (package:image_cropping/image_cropping.dart:264:20)
E/flutter (11146): #3      _ImageCroppingScreenState.initState (package:image_cropping/image_cropping.dart:191:5)
E/flutter (11146): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5101:55)
E/flutter (11146): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377:14)
E/flutter (11146): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377:14)
E/flutter (11146): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377:14)
E/flutter (11146): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377:14)
E/flutter (11146): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377:14)
E/flutter (11146): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #46     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #49     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #54     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #57     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377:14)
E/flutter (11146): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #65     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #72     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377:14)
E/flutter (11146): #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #76     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #79     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #87     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #98     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #101    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #102    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #105    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377:14)
E/flutter (11146): #106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #109    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #110    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #111    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #114    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377:14)
E/flutter (11146): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #118    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #119    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #120    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #121    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #122    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #126    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #127    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #138    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #140    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #141    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #142    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #147    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #148    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #150    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #152    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #153    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #154    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #155    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #157    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377:14)
E/flutter (11146): #158    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #159    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #161    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #162    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #163    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #164    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #165    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #167    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #168    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #169    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #171    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #173    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #174    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #175    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #176    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #177    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #178    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #179    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #181    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #182    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #183    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #184    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #185    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #186    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #187    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #188    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #189    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #190    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #191    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #192    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #193    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #194    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #195    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #196    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377:14)
E/flutter (11146): #197    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #198    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #200    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #201    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #202    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #203    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #204    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #206    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #207    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #208    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #209    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #210    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #211    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #212    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #214    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #215    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #216    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
E/flutter (11146): #217    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
E/flutter (11146): #218    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
E/flutter (11146): #219    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
E/flutter (11146): #220    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
E/flutter (11146): #221    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
E/flutter (11146): #222    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6041:32)
E/flutter (11146): #223    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
E/flutter (11146): #224    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
E/flutter (11146): #225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #226    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #227    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #228    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
E/flutter (11146): #229    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
E/flutter (11146): #230    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #231    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #232    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
E/flutter (11146): #233    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
E/flutter (11146): #234    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #235    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #236    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
E/flutter (11146): #237    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
E/flutter (11146): #238    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
E/flutter (11146): #239    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #240    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #241    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #242    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
E/flutter (11146): #243    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
E/flutter (11146): #244    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #245    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #246    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
E/flutter (11146): #247    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
E/flutter (11146): #248    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
E/flutter (11146): #249    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #250    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #251    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #252    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
E/flutter (11146): #253    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
E/flutter (11146): #254    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #255    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #256    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
E/flutter (11146): #257    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
E/flutter (11146): #258    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #259    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #260    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #261    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
E/flutter (11146): #262    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
E/flutter (11146): #263    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
E/flutter (11146): #264    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
E/flutter (11146): #265    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
E/flutter (11146): #266    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
E/flutter (11146): #267    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #268    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #269    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
E/flutter (11146): #270    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
E/flutter (11146): #271    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
E/flutter (11146): #272    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
E/flutter (11146): #273    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
E/flutter (11146): #274    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
E/flutter (11146): #275    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
E/flutter (11146): #276    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
E/flutter (11146): #277    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
E/flutter (11146): #278    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
E/flutter (11146): #279    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
E/flutter (11146): #280    _rootRun (dart:async/zone.dart:1398:13)
E/flutter (11146): #281    _CustomZone.run (dart:async/zone.dart:1300:19)
E/flutter (11146): #282    _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
E/flutter (11146): #283    _invoke (dart:ui/hooks.dart:147:10)
E/flutter (11146): #284    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
E/flutter (11146): #285    _drawFrame (dart:ui/hooks.dart:112:31)

**Comment by AnujMI297** [comment]
@AccruonSahin, We are unable to reproduce this same problem, can you please share the steps to reproduce this issue or can you provide us with more detail about this?

**Comment by AccruonSahin** [comment]
@AnujMI297, Thank the issue is with file picker package
