### ISSUE TITLE
Wrong are cropping issue

### ISSUE THREAD

**Issue by worldwidee** [Mindinventory/image_cropping#2]
Hi! I am so thankful. your package is looks very nice and useful. But when i try to crop image as 1/1 , the result shape should be square. Actually it never really crops right. the result stays to the left of which is clipped. Is this happening only to me? I am working on windows by the way.

**Comment by mi-ghanshyam** [comment]
@furkan1023  I just checked in the latest version and it's working for me.  Can you please provide me screen recording video of this issue?
Also, please verify in the latest version `image_cropping: 0.0.8`

I am happy to help you!
Thanks!

**Comment by abhimanyu95** [comment]
on the Web, It Freezes the UI when Opening the Cropper and after cropping, on both times it freezes.
