### ISSUE TITLE
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/image_crop-0.4.1/lib/src/crop.dart:63:68: Error: The class 'Drag' can't be used as a mixin because it isn't a mixin class nor a mixin

### ISSUE THREAD

**Issue by minh-dai** [Mindinventory/image_cropping#22]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.1 23B74 darwin-x64)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.2)

**Comment by abrarmalekji345** [comment]
@minh-dai it seems you have added the issue at the wrong place, closing as it is irrelevant. please let me know if you have any concerns with this package. Thanks.
