### ISSUE TITLE
Initial crop marker size

### ISSUE THREAD

**Issue by sharpsaravanan** [Mindinventory/image_cropping#23]
Thank you for great package, 

Add a parameter to choose initial crop marker size to be entire image width, height or default(Center)

**Comment by chelsiprajapatimi** [comment]
@sharpsaravanan 

Thank you for your feedback! I’ve added a new `useInitialFullCrop` property to address this. You can now use it to set the initial crop marker size to the entire image width, and height. Let me know if you have any other suggestions!
